import React, { useState } from 'react';
import { LayoutDashboard, Library, MessageSquareText, BookA, Menu, X, Database, Bot, Globe, Download, FileDown, GraduationCap, Languages, Link } from 'lucide-react';
import { CorpusDocument, DocumentType, Language, SourceType } from './types';
import { tokenize, analyzeSentiment, cleanCorpusText } from './utils/nlp';
import { translations } from './utils/translations';
import { simulateClassroomFetch } from './services/geminiService';
import FileUploader from './components/FileUploader';
import AnalysisView from './components/AnalysisView';
import AIChat from './components/AIChat';
import GlossaryView from './components/GlossaryView';
import CorpusBuilder from './components/CorpusBuilder';
import TranslatorView from './components/TranslatorView';
import JSZip from 'jszip';

enum Tab {
  DASHBOARD = 'dashboard',
  BUILDER = 'builder',
  ANALYSIS = 'analysis',
  CHAT = 'chat',
  GLOSSARY = 'glossary',
  TRANSLATOR = 'translator'
}

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Tab>(Tab.DASHBOARD);
  const [documents, setDocuments] = useState<CorpusDocument[]>([]);
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [uiLang, setUiLang] = useState<'EN' | 'ES'>('ES'); 
  
  // Classroom States
  const [isImportingClassroom, setIsImportingClassroom] = useState(false);
  const [classUrl, setClassUrl] = useState('');
  const [classTask, setClassTask] = useState('');

  const t = translations[uiLang];

  const handleUpload = (title: string, content: string, type: DocumentType, lang: Language) => {
    // Apply clean text function on upload
    const cleanedContent = cleanCorpusText(content);
    const sentiment = analyzeSentiment(cleanedContent, lang);
    
    const newDoc: CorpusDocument = {
      id: Math.random().toString(36).substr(2, 9),
      title,
      content: cleanedContent,
      type,
      language: lang,
      sourceType: SourceType.MANUAL_UPLOAD,
      tokenCount: tokenize(cleanedContent).length,
      uploadDate: new Date().toLocaleDateString(),
      sentiment: sentiment,
      author: 'Unknown',
      sourceUrl: 'Local File'
    };
    setDocuments(prev => [...prev, newDoc]);
  };

  const handleAutoGeneratedDocs = (newDocs: CorpusDocument[]) => {
    setDocuments(prev => [...prev, ...newDocs]);
  };

  const handleClassroomImport = async () => {
      if (!classUrl.trim() || !classTask.trim()) {
          alert(uiLang === 'EN' ? 'Please enter URL and Task Name' : 'Por favor ingresa la URL y el Nombre de la Tarea');
          return;
      }
      setIsImportingClassroom(true);
      try {
          const docs = await simulateClassroomFetch(classUrl, classTask);
          const processedDocs = docs.map(d => ({
              ...d,
              id: Math.random().toString(36).substr(2, 9),
              tokenCount: tokenize(d.content).length,
              uploadDate: new Date().toLocaleDateString(),
              sentiment: analyzeSentiment(d.content, d.language),
              type: DocumentType.TEXT, // Ensure type matches enum
              sourceUrl: d.url
          } as CorpusDocument));
          
          setDocuments(prev => [...prev, ...processedDocs]);
          // Clear inputs after success
          setClassUrl('');
          setClassTask('');
          alert(`Imported ${docs.length} assignments from "${classTask}".`);
      } catch (error) {
          console.error(error);
          alert("Error connecting to Classroom simulator.");
      } finally {
          setIsImportingClassroom(false);
      }
  };

  const handleDownloadZip = async () => {
      if (documents.length === 0) return;
      
      const zip = new JSZip();
      const root = zip.folder("Biblioteca de Corpus - CMBI");
      if(!root) return;

      const topicName = "General_Collection";
      const topicFolder = root.folder(topicName);
      
      const enFolder = topicFolder?.folder("Ingles");
      const esFolder = topicFolder?.folder("Espanol");

      let enCount = 1;
      let esCount = 1;
      let metadataRows = "Filename,Source URL,Author,Date,Title\n";

      documents.forEach(doc => {
          let filename = "";
          let folder = null;

          if (doc.language === Language.ENGLISH) {
             filename = `en${String(enCount).padStart(2, '0')}.txt`;
             folder = enFolder;
             enCount++;
          } else {
             filename = `es${String(esCount).padStart(2, '0')}.txt`;
             folder = esFolder;
             esCount++;
          }

          if (folder) {
              folder.file(filename, doc.content);
              metadataRows += `${filename},"${doc.sourceUrl || 'N/A'}","${doc.author || 'N/A'}","${doc.uploadDate}","${doc.title}"\n`;
          }
      });

      if(topicFolder) topicFolder.file("metadata.csv", metadataRows);

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "CMBI_Corpus_Library.zip";
      a.click();
      URL.revokeObjectURL(url);
  };

  const handleDownloadSingleFile = () => {
      if (documents.length === 0) return;
      
      const allContent = documents.map(d => `### ${d.title} (${d.language})\n${d.content}\n\n`).join("------------------------------------------------\n");
      const blob = new Blob([allContent], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "Full_Corpus_Concatenated.txt";
      a.click();
      URL.revokeObjectURL(url);
  };

  const toggleSidebar = () => setIsSidebarOpen(!isSidebarOpen);
  const toggleLanguage = () => setUiLang(prev => prev === 'EN' ? 'ES' : 'EN');

  return (
    <div className="flex h-screen overflow-hidden bg-slate-50 font-inter">
      {/* Mobile Sidebar Overlay */}
      {isSidebarOpen && (
        <div className="fixed inset-0 bg-black/50 z-20 lg:hidden" onClick={toggleSidebar}></div>
      )}

      {/* Sidebar */}
      <aside className={`fixed lg:static inset-y-0 left-0 z-30 w-64 bg-slate-900 text-white transform transition-transform duration-300 lg:transform-none flex flex-col ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="p-6 flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="bg-indigo-500 p-2 rounded-lg">
              <Database className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-xl font-bold tracking-tight">CMBI</h1>
              <p className="text-xs text-slate-400">Corpus Lab</p>
            </div>
          </div>
          <button 
            onClick={toggleLanguage} 
            className="p-1.5 rounded-md hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
            title="Switch Language"
          >
            <Globe className="w-5 h-5" />
            <span className="sr-only">{uiLang === 'EN' ? 'ES' : 'EN'}</span>
          </button>
        </div>
        
        <nav className="p-4 space-y-2 flex-1 overflow-y-auto">
          <button 
            onClick={() => { setActiveTab(Tab.DASHBOARD); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-colors ${activeTab === Tab.DASHBOARD ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}
          >
            <LayoutDashboard className="w-5 h-5" />
            <span className="font-medium">{t.manageCorpus}</span>
          </button>

          <button 
            onClick={() => { setActiveTab(Tab.BUILDER); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-colors ${activeTab === Tab.BUILDER ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}
          >
            <Bot className="w-5 h-5" />
            <span className="font-medium">{t.autoBuild}</span>
          </button>
          
          <button 
            onClick={() => { setActiveTab(Tab.ANALYSIS); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-colors ${activeTab === Tab.ANALYSIS ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}
          >
            <Library className="w-5 h-5" />
            <span className="font-medium">{t.analysis}</span>
          </button>
          
          <button 
            onClick={() => { setActiveTab(Tab.CHAT); setIsSidebarOpen(false); }}
            className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-colors ${activeTab === Tab.CHAT ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}
          >
            <MessageSquareText className="w-5 h-5" />
            <span className="font-medium">{t.aiInquiry}</span>
          </button>
          
          <button 
             onClick={() => { setActiveTab(Tab.GLOSSARY); setIsSidebarOpen(false); }}
             className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-colors ${activeTab === Tab.GLOSSARY ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}
          >
            <BookA className="w-5 h-5" />
            <span className="font-medium">{t.glossary}</span>
          </button>

          <button 
             onClick={() => { setActiveTab(Tab.TRANSLATOR); setIsSidebarOpen(false); }}
             className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-colors ${activeTab === Tab.TRANSLATOR ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}
          >
            <Languages className="w-5 h-5" />
            <span className="font-medium">{t.translator}</span>
          </button>
        </nav>

        <div className="p-6 bg-slate-900 z-10">
           <div className="bg-slate-800 rounded-xl p-4 shadow-lg border border-slate-700">
             <p className="text-xs text-slate-400 mb-1">{t.totalDocs}</p>
             <p className="text-3xl font-bold text-white">{documents.length}</p>
             <p className="text-[10px] text-slate-500 mt-2 border-t border-slate-700 pt-2 uppercase tracking-wider flex items-center gap-1">
               <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse"></span>
               {t.geminiActive}
             </p>
           </div>
        </div>
      </aside>

      <main className="flex-1 flex flex-col h-full overflow-hidden">
        <header className="bg-white border-b border-slate-200 p-4 flex items-center justify-between lg:hidden">
            <div className="flex items-center gap-2">
                <span className="font-bold text-slate-800">CMBI</span>
            </div>
            <button onClick={toggleSidebar} className="p-2 text-slate-600 hover:bg-slate-100 rounded-lg">
                {isSidebarOpen ? <X className="w-6 h-6"/> : <Menu className="w-6 h-6"/>}
            </button>
        </header>

        <div className="flex-1 overflow-y-auto p-4 lg:p-8">
            <div className="max-w-6xl mx-auto h-full">
                {activeTab === Tab.DASHBOARD && (
                    <div className="space-y-8 animate-fade-in">
                        <div className="flex flex-wrap items-center justify-between gap-4">
                            <div>
                                <h2 className="text-2xl font-bold text-slate-900">{t.corpusManagement}</h2>
                                <p className="text-slate-500">{t.corpusDesc}</p>
                            </div>
                            <div className="flex gap-2">
                                <button 
                                    onClick={() => setActiveTab(Tab.BUILDER)} 
                                    className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-medium transition-colors shadow-sm"
                                >
                                    <Bot className="w-4 h-4" /> {t.openBuilder}
                                </button>
                            </div>
                        </div>
                        
                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                            <div className="lg:col-span-2">
                                <FileUploader onUpload={handleUpload} uiLang={uiLang} />
                            </div>
                            <div className="bg-amber-50 border border-amber-200 rounded-xl p-5 shadow-sm">
                                <div className="flex items-center gap-2 mb-3 text-amber-800">
                                    <GraduationCap className="w-5 h-5" />
                                    <h3 className="font-semibold">{t.classroomTitle}</h3>
                                </div>
                                <div className="space-y-3">
                                    <div className="relative">
                                        <Link className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-amber-400" />
                                        <input 
                                            type="text" 
                                            value={classUrl}
                                            onChange={(e) => setClassUrl(e.target.value)}
                                            placeholder={t.classroomUrlPlaceholder}
                                            className="w-full pl-9 pr-3 py-2 text-sm border border-amber-200 rounded-lg focus:ring-2 focus:ring-amber-500 focus:outline-none bg-white"
                                        />
                                    </div>
                                    <input 
                                        type="text" 
                                        value={classTask}
                                        onChange={(e) => setClassTask(e.target.value)}
                                        placeholder={t.classroomTaskPlaceholder}
                                        className="w-full px-3 py-2 text-sm border border-amber-200 rounded-lg focus:ring-2 focus:ring-amber-500 focus:outline-none bg-white"
                                    />
                                    <button 
                                        onClick={handleClassroomImport}
                                        disabled={isImportingClassroom}
                                        className="w-full bg-amber-500 hover:bg-amber-600 text-white py-2 rounded-lg text-sm font-medium transition-colors flex justify-center items-center gap-2"
                                    >
                                        {isImportingClassroom ? <span className="animate-spin">⟳</span> : <GraduationCap className="w-4 h-4" />}
                                        {t.classroomBtn}
                                    </button>
                                </div>
                            </div>
                        </div>

                        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                            <div className="px-6 py-4 border-b border-slate-100 font-semibold text-slate-800 flex justify-between items-center">
                                <div className="flex items-center gap-4">
                                    <span>{t.docsInMemory}</span>
                                    <span className="bg-slate-100 text-slate-600 px-2 py-0.5 rounded-full text-xs">{documents.length}</span>
                                </div>
                                <div className="flex gap-2">
                                    <button 
                                        onClick={handleDownloadZip}
                                        disabled={documents.length === 0}
                                        className="flex items-center gap-1 text-xs bg-slate-100 hover:bg-slate-200 text-slate-700 px-3 py-1.5 rounded-lg transition-colors"
                                        title="Zip Folder Structure"
                                    >
                                        <Download className="w-3 h-3" /> {t.downloadZip}
                                    </button>
                                     <button 
                                        onClick={handleDownloadSingleFile}
                                        disabled={documents.length === 0}
                                        className="flex items-center gap-1 text-xs bg-slate-100 hover:bg-slate-200 text-slate-700 px-3 py-1.5 rounded-lg transition-colors"
                                        title="Concatenated TXT"
                                    >
                                        <FileDown className="w-3 h-3" /> {t.downloadSingle}
                                    </button>
                                </div>
                            </div>
                            {documents.length === 0 ? (
                                <div className="p-8 text-center text-slate-400">{t.noDocs}</div>
                            ) : (
                                <table className="w-full text-left text-sm">
                                    <thead className="bg-slate-50">
                                        <tr>
                                            <th className="px-6 py-3 font-medium text-slate-500">{t.tableTitle}</th>
                                            <th className="px-6 py-3 font-medium text-slate-500">{t.tableSource}</th>
                                            <th className="px-6 py-3 font-medium text-slate-500">{t.tableType}</th>
                                            <th className="px-6 py-3 font-medium text-slate-500">{t.tableLang}</th>
                                            <th className="px-6 py-3 font-medium text-slate-500">{t.tableTokens}</th>
                                            <th className="px-6 py-3 font-medium text-slate-500">{t.tableSentiment}</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-100">
                                        {documents.map(doc => (
                                            <tr key={doc.id} className="hover:bg-slate-50 transition-colors">
                                                <td className="px-6 py-3 font-medium text-slate-800 max-w-[200px] truncate" title={doc.title}>{doc.title}</td>
                                                <td className="px-6 py-3 text-slate-500 text-xs truncate max-w-[150px]">{doc.sourceType || SourceType.MANUAL_UPLOAD}</td>
                                                <td className="px-6 py-3">
                                                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                                        doc.type === DocumentType.AUDIO ? 'bg-amber-100 text-amber-700' :
                                                        doc.type === DocumentType.VIDEO ? 'bg-rose-100 text-rose-700' :
                                                        'bg-blue-100 text-blue-700'
                                                    }`}>
                                                        {doc.type}
                                                    </span>
                                                </td>
                                                <td className="px-6 py-3 text-slate-600">{doc.language}</td>
                                                <td className="px-6 py-3 text-slate-600 font-mono">{doc.tokenCount.toLocaleString()}</td>
                                                <td className="px-6 py-3">
                                                   {doc.sentiment && (
                                                       <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                                                           doc.sentiment.label === 'Positive' ? 'bg-emerald-100 text-emerald-700' :
                                                           doc.sentiment.label === 'Negative' ? 'bg-red-100 text-red-700' :
                                                           'bg-slate-100 text-slate-600'
                                                       }`}>
                                                           {doc.sentiment.label}
                                                       </span>
                                                   )}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            )}
                        </div>
                    </div>
                )}

                {activeTab === Tab.BUILDER && (
                    <CorpusBuilder onDocsGenerated={handleAutoGeneratedDocs} uiLang={uiLang} />
                )}

                {activeTab === Tab.ANALYSIS && (
                    <AnalysisView documents={documents} uiLang={uiLang} />
                )}

                {activeTab === Tab.CHAT && (
                    <AIChat documents={documents} uiLang={uiLang} />
                )}
                
                {activeTab === Tab.GLOSSARY && (
                    <GlossaryView documents={documents} uiLang={uiLang} />
                )}

                {activeTab === Tab.TRANSLATOR && (
                    <TranslatorView uiLang={uiLang} onDocsGenerated={handleAutoGeneratedDocs} />
                )}
            </div>
        </div>
      </main>
    </div>
  );
};

export default App;